### ISSUE TITLE
Flickering links between moving devices

### ISSUE THREAD

**Issue by jakebeal** [DanySK/alchemist-maps#4]
Devices following a GPS trace have links that flicker, coming and going as they move.  They are mostly present as expected, but sometimes unpredictably vanish for short periods.
I don't know whether this is map-specific or happens in all simulations.

**Comment by DanySK** [comment]
This may actually be a deep rooted bug. I think I have a clue, I am preparing a test case to force the bug to show.

**Comment by DanySK** [comment]
The node positioning caching has been completely revisited. The bug should be no more. The is now propagated, and will hit the next Alchemist release.
