### ISSUE TITLE
Maps slow and then freeze after a couple of reloads

### ISSUE THREAD

**Issue by jakebeal** [DanySK/alchemist-maps#6]
Each time a map with devices moving along GPS traces gets reloaded, everything slows down.  After a couple of reloads, Alchemist freezes up and fails to complete reloading.

**Comment by DanySK** [comment]
Sounds to me as a memory leak: the java heap space runs towards its limit, the garbage collector kicks in more and more frequently (hence the slowness) up until there is an out of memory and everything dies badly.

Can you take a look to the alchemist process' memory usage?

**Comment by jakebeal** [comment]
Initial memory: 184 MB
After first load: 485 MB
After second load: 521 MB
After third load: 627 MB

**Comment by DanySK** [comment]
Yes, this is a roaring memory leak. Can you send me (also in private if you like) the psim file that generates such behavior?

**Comment by DanySK** [comment]
That bug should be solved now, it was a UI bug. The fix will be shipped in the next Alchemist release (along with a way to pull up the UI on demand for a single experiment, à-la Proto).
